### PR TITLE
Add support for ruby 3.0.x

### PR DESCRIPTION
**Pull request by alachaum**
- Refactor positional/keyword arguments to support ruby 3.0.x
- Separate test environments for ruby 2.5/2.6 / 2.7 / 3.x
- Skip Rails-specific tests when Rails in not in context

### CODE REVIEW

**Comment by vovimayhem** [comment]
Oh great!!!! I was actually bumping my head with this one when upgrading an app to ruby 3... what else is needed?

**Comment by vovimayhem** [comment]
I'm still getting an error when setting up a queue on Ruby 3.0.3, right where we're checking if the queue exists or not:

```ruby
require 'cloudtasker/backend/google_cloud_task'
require 'cloudtasker/config'
Cloudtasker::Backend::GoogleCloudTask.setup_queue(name: "default")
```

Throws:

```
/usr/local/bundle/gems/google-cloud-tasks-1.5.1/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb:523:in `create_queue': wrong number of arguments (given 1, expected 2) (ArgumentError)
/usr/local/bundle/gems/google-gax-1.8.2/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable': GaxError Exception occurred in retry method that was not classified as transient, caused by 5:Queue does not exist. If you just created the queue, wait at least a minute for the queue to initialize.. debug_error_string:{"created":"@1641166932.545747842","description":"Error received from peer ipv4:142.250.65.138:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Queue does not exist. If you just created the queue, wait at least a minute for the queue to initialize.","grpc_status":5} (Google::Gax::RetryError)
/usr/local/bundle/gems/grpc-1.42.0/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 5:Queue does not exist. If you just created the queue, wait at least a minute for the queue to initialize.. debug_error_string:{"created":"@1641166932.545747842","description":"Error received from peer ipv4:142.250.65.138:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Queue does not exist. If you just created the queue, wait at least a minute for the queue to initialize.","grpc_status":5} (GRPC::NotFound)
```

**Comment by vovimayhem** [comment]
The test at [spec/cloudtasker/backend/google_cloud_task_spec.rb:37](https://github.com/keypup-io/cloudtasker/blob/22ee4fee93f5252f0fc3c33cd35f5f54c51edfcc/spec/cloudtasker/backend/google_cloud_task_spec.rb#L37) is covering the call, but the latest `rspec-mocks` has yet to include the rspec/rspec-mocks#1394 fix "Make with support Ruby 3 keywords"... hence it's not being detected...

How about switching `rspec-mocks` to git until it gets released?

**Comment by vovimayhem** [comment]
https://github.com/rspec/rspec-mocks/issues/1425

**Comment by alachaum** [comment]
Thanks for the testing @vovimayhem ! I was actually planning to do another round of testing over the next couple of days. Ideally I want to merge this PR this week and make a release candidate.

**Comment by alachaum** [comment]
@vovimayhem release candidate `v0.13.rc1` has been pushed to rubygems! Feel free to provide feedback on the [original issue](https://github.com/keypup-io/cloudtasker/issues/27)

**Comment by vovimayhem** [comment]
I tried to make the specs detect that, but had no luck - I guess that rspec has yet to get the hash vs keywords thing right...

**Pull request merged**
